---
name: homelab

include:
  - path: compose/media.yaml
    project_directory: .
  - path: compose/network.yaml
    project_directory: .
  - path: compose/vpn.yaml
    project_directory: .
  - path: compose/monitoring.yaml
    project_directory: .
  - path: compose/iot.yaml
    project_directory: .
