---
services:
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ./appdata/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "127.0.0.1:8081:8080"
    devices:
      - ${ZIGBEE_ADAPTER_PATH}:${ZIGBEE_ADAPTER_PATH}
    group_add:
      - ${ZIGBEE_ADAPTER_GROUP}
    networks:
      - proxy
      - iot
    profiles:
      - iot
      - all
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ./appdata/mosquitto/config:/mosquitto/config
      - ./appdata/mosquitto/data:/mosquitto/data
      - ./appdata/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - proxy
      - iot
    profiles:
      - iot
      - all
    restart: unless-stopped

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ./appdata/homeassistant:/config
    ports:
      - "127.0.0.1:8123:8123"
    networks:
      - proxy
      - iot
    profiles:
      - iot
      - all
    restart: unless-stopped

networks:
  proxy:
  iot:
