---
services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    volumes:
      - ./appdata/adguard/work:/opt/adguardhome/work
      - ./appdata/adguard/conf:/opt/adguardhome/conf
    network_mode: host
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
    profiles:
      - network
      - all
    restart: unless-stopped

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.14.0@sha256:a142e4adf94638fe4f2a28fa1bae87ca590e11010bf1ec5babf8b06d54fb1d1c
    container_name: nginx-proxy-manager
    volumes:
      - ./appdata/nginx-proxy-manager/data:/data
      - ./appdata/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:81:81"
    networks:
      - proxy
    profiles:
      - network
      - all
    restart: unless-stopped

networks:
  proxy:
